/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/articles': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The article list response schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            content: {
                                /** @description The article id */
                                id: number;
                                /** @description The article title */
                                title: string;
                                /** @description The article content */
                                content: string;
                                /**
                                 * Format: date-time
                                 * @description The article created at
                                 */
                                createdAt: string;
                                /**
                                 * Format: date-time
                                 * @description The article updated at
                                 */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The article creation schema */
            requestBody: {
                content: {
                    'application/json': {
                        /** @description The article title */
                        title: string;
                        /** @description The article content */
                        content: string;
                    };
                };
            };
            responses: {
                /** @description The article creation response schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/articles/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The article id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The article response schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** @description The article id */
                            id: number;
                            /** @description The article title */
                            title: string;
                            /** @description The article content */
                            content: string;
                            /**
                             * Format: date-time
                             * @description The article created at
                             */
                            createdAt: string;
                            /**
                             * Format: date-time
                             * @description The article updated at
                             */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The article id */
                    id: string;
                };
                cookie?: never;
            };
            /** @description The article update schema */
            requestBody: {
                content: {
                    'application/json': {
                        /** @description The article title */
                        title?: string;
                        /** @description The article content */
                        content?: string;
                    };
                };
            };
            responses: {
                /** @description Article updated successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The article id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Article deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/signup': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The user sign up schema */
            requestBody: {
                content: {
                    'application/json': {
                        /** @description The user login id */
                        loginId: string;
                        /** @description The user password */
                        password: string;
                        /** @description The user name */
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description The authentication response schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** @description The access token (JWT) */
                            access_token: string;
                            /** @description The refresh token (JWT) */
                            refresh_token: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/login': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The user login schema */
            requestBody: {
                content: {
                    'application/json': {
                        /** @description The user login id */
                        loginId: string;
                        /** @description The user password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description The authentication response schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** @description The access token (JWT) */
                            access_token: string;
                            /** @description The refresh token (JWT) */
                            refresh_token: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/refresh': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The refresh token schema */
            requestBody: {
                content: {
                    'application/json': {
                        /** @description The refresh token */
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description The authentication response schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** @description The access token (JWT) */
                            access_token: string;
                            /** @description The refresh token (JWT) */
                            refresh_token: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/api/users/me': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current user details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** @description The user ulid */
                            ulid: string;
                            /** @description The user role */
                            role: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
